// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Job_Status")]
public partial class Job_Status
{
    [Key]
    public int StatusType { get; set; }

    [StringLength(50)]
    public string StatusName { get; set; }
}