// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Job_Part_inStore")]
public partial class Job_Part_inStore
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    [StringLength(50)]
    public string Barcode { get; set; }

    public string PartNameEng { get; set; }

    public string PartNameThai { get; set; }

    public int? JobID { get; set; }

    public int? Quantity { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifyOn { get; set; }

    [StringLength(50)]
    public string PrNo { get; set; }

    [StringLength(50)]
    public string PONo { get; set; }
}