// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Job_NameJob")]
public partial class Job_NameJob
{
    [Key]
    public int ID { get; set; }

    public string JobName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FinishAt { get; set; }

    [StringLength(50)]
    public string ResponsiblePerson { get; set; }

    public int? Status { get; set; }
}