// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[PrimaryKey("DateTime", "Barcode")]
[Table("Job_partLog")]
public partial class Job_partLog
{
    [Key]
    [Column(TypeName = "datetime")]
    public DateTime DateTime { get; set; }

    [Key]
    [StringLength(50)]
    public string Barcode { get; set; }

    public string PartNameEng { get; set; }

    public string PartNameThai { get; set; }

    public int? JobID { get; set; }

    public int? EventType { get; set; }

    public int? Quantity { get; set; }

    [StringLength(50)]
    public string PRNo { get; set; }

    [StringLength(50)]
    public string PONo { get; set; }

    public string Description { get; set; }

    public string Reveal_Name { get; set; }
}