// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Job_EventType")]
public partial class Job_EventType
{
    [Key]
    public int Type { get; set; }

    [StringLength(50)]
    public string EventName { get; set; }
}