// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_Approve")]
public partial class Store_Approve
{
    [Key]
    public int ID { get; set; }

    public int Apporve_Type { get; set; }

    public string Apporve_Type_Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int? Request_ID { get; set; }

    public string Request_Name { get; set; }

    public int? Apporve_By_ID { get; set; }

    public string Apporve_By_Name { get; set; }

    public int? Apporve_status { get; set; }

    public string Apporve_Text { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Apporve_date { get; set; }

    public string Reason { get; set; }

    public int? Referent_EventID { get; set; }
}