// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_PickUp_Detail")]
public partial class Store_PickUp_Detail
{
    [Key]
    public int ID { get; set; }

    public int PickUpID { get; set; }

    [Required]
    [StringLength(50)]
    public string ID_Product { get; set; }

    public string Name_TH { get; set; }

    public string Name_EN { get; set; }

    public int Item_QUANTITY { get; set; }

    [ForeignKey("PickUpID")]
    [InverseProperty("Store_PickUp_Details")]
    public virtual Store_PickUp PickUp { get; set; }
}