// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_EditPart")]
public partial class Store_EditPart
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeStamp { get; set; }

    [Required]
    [StringLength(50)]
    public string ID_Product { get; set; }

    [Required]
    public string Maker { get; set; }

    public string Before_NameEng { get; set; }

    public string Before_NameTH { get; set; }

    public int? Before_Quantity { get; set; }

    [StringLength(50)]
    public string Before_Unit { get; set; }

    public double? Before_UNIT_PRICE { get; set; }

    public string Before_Location { get; set; }

    public bool? Before_status { get; set; }

    public int? Before_SupplierID { get; set; }

    public string After_NameEng { get; set; }

    public string After_NameTH { get; set; }

    public int? After_Quantity { get; set; }

    [StringLength(50)]
    public string After_Unit { get; set; }

    public double? After_UNIT_PRICE { get; set; }

    public string After_Location { get; set; }

    public bool? After_status { get; set; }

    public int? ApproveID { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }

    public int? After_SupplierID { get; set; }
}