// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_Part")]
public partial class Store_Part
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    public string ID_Product { get; set; }

    [Required]
    public string NAME_PRODUCT_ENG { get; set; }

    [Required]
    public string NAME_PRODUCT_TH { get; set; }

    [Required]
    public string MAKER { get; set; }

    public int? SupplierID { get; set; }

    public int QUANTITY { get; set; }

    [StringLength(50)]
    public string UNIT { get; set; }

    public double? UNIT_PRICE { get; set; }

    public string Description { get; set; }

    public string Location { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created_On { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Modify_On { get; set; }

    public bool status { get; set; }
}