// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_AddQTY")]
public partial class Store_AddQTY
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeStamp { get; set; }

    [Required]
    [StringLength(50)]
    public string ID_Product { get; set; }

    [Required]
    [StringLength(50)]
    public string Maker { get; set; }

    public int? LastQuantity { get; set; }

    public int? AddToStock { get; set; }

    public int? Quantity { get; set; }

    public int? ApproveID { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }
}