// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_AddSupplier")]
public partial class Store_AddSupplier
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeStamp { get; set; }

    [Required]
    [StringLength(50)]
    public string SupplierID { get; set; }

    [Required]
    public string SupplierName { get; set; }

    public string AddressDetail { get; set; }

    public string Country { get; set; }

    public string Province { get; set; }

    public string District { get; set; }

    public string Sub_District { get; set; }

    public int? PostCode { get; set; }

    public string Email { get; set; }

    public string Email2 { get; set; }

    public string FirstName1 { get; set; }

    public string LastName1 { get; set; }

    public string MobileNumber1 { get; set; }

    public string FirstName2 { get; set; }

    public string LastName2 { get; set; }

    public string MobileNumber2 { get; set; }

    public string PhoneNumber1 { get; set; }

    public string PhoneNumber2 { get; set; }

    public string Fax1 { get; set; }

    public string Fax2 { get; set; }

    public int? Credit { get; set; }

    [StringLength(50)]
    public string Account_No { get; set; }

    public string Maker { get; set; }

    public int? ApproveID { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }
}