// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_Do")]
public partial class Store_Do
{
    [Key]
    public int ID { get; set; }

    public DateTime Date { get; set; }

    [StringLength(10)]
    public string SupplierID { get; set; }

    [StringLength(50)]
    public string InputBy { get; set; }

    public DateTime? InputDate { get; set; }

    public int? ApproveID { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }

    public string Comment { get; set; }

    [InverseProperty("DO")]
    public virtual ICollection<Store_Do_Datail> Store_Do_Datails { get; set; } = new List<Store_Do_Datail>();
}