// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_PickUp")]
public partial class Store_PickUp
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(50)]
    public string Job { get; set; }

    [Required]
    [StringLength(50)]
    public string Machine_Code { get; set; }

    [StringLength(50)]
    public string PickUpBy { get; set; }

    [Required]
    [StringLength(50)]
    public string User_ID { get; set; }

    [Required]
    public string Reveal_Name { get; set; }

    public string Description { get; set; }

    public int Total { get; set; }

    [StringLength(50)]
    public string Remark { get; set; }

    public int? ApproveID { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }

    [InverseProperty("PickUp")]
    public virtual ICollection<Store_PickUp_Detail> Store_PickUp_Details { get; set; } = new List<Store_PickUp_Detail>();
}