// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_Do_Datail")]
public partial class Store_Do_Datail
{
    [Key]
    public int ID { get; set; }

    public int DO_ID { get; set; }

    [StringLength(50)]
    public string ID_Product { get; set; }

    public int? Quantity { get; set; }

    [StringLength(50)]
    public string Unit { get; set; }

    public double? Unit_Price { get; set; }

    [ForeignKey("DO_ID")]
    [InverseProperty("Store_Do_Datails")]
    public virtual Store_Do DO { get; set; }
}