// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Keyless]
[Table("Store_DeleteSupplier")]
public partial class Store_DeleteSupplier
{
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeStamp { get; set; }

    [Required]
    [StringLength(50)]
    public string SupplierID { get; set; }

    public string Maker { get; set; }

    public string Description { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }

    public int? ApproveID { get; set; }
}