// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_AddPart")]
public partial class Store_AddPart
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TimeStamp { get; set; }

    [Required]
    [StringLength(50)]
    public string ID_Product { get; set; }

    [Required]
    [StringLength(50)]
    public string PartGroupType { get; set; }

    [Required]
    public string NAME_PRODUCT_ENG { get; set; }

    [Required]
    public string NAME_PRODUCT_TH { get; set; }

    [Required]
    public string Maker { get; set; }

    public int? SupplierID { get; set; }

    public int QUANTITY { get; set; }

    [StringLength(50)]
    public string UNIT { get; set; }

    public double? UNIT_PRICE { get; set; }

    public string Description { get; set; }

    public string Location { get; set; }

    public int? ApproveID { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApproveTime { get; set; }

    [ForeignKey("SupplierID")]
    [InverseProperty("Store_AddParts")]
    public virtual Store_Supplier Supplier { get; set; }
}