// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Store_PartGroup")]
public partial class Store_PartGroup
{
    [Key]
    [StringLength(50)]
    public string ID_TYPE { get; set; }

    public string NAME_GROUP_EN { get; set; }

    public string NAME_GROUP_TH { get; set; }

    public bool Status { get; set; }
}