// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Tool_BorrowDetail")]
public partial class Tool_BorrowDetail
{
    [Key]
    public int ID { get; set; }

    public int BorrowID { get; set; }

    [Required]
    [StringLength(50)]
    public string Tool { get; set; }

    public int Quantity { get; set; }

    [Required]
    [StringLength(50)]
    public string Unit { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReturnAt { get; set; }

    [ForeignKey("BorrowID")]
    [InverseProperty("Tool_BorrowDetails")]
    public virtual Tool_Borrow Borrow { get; set; }
}