// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

public partial class Tool
{
    [Key]
    public int ID { get; set; }

    [StringLength(500)]
    public string Name_ENG { get; set; }

    [StringLength(500)]
    public string Name_TH { get; set; }

    public int? Quantity { get; set; }

    [StringLength(50)]
    public string Unit { get; set; }

    [StringLength(500)]
    public string Location { get; set; }

    public string Picture { get; set; }

    [StringLength(500)]
    public string Supplier { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifyOn { get; set; }
}