// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Tool_Event")]
public partial class Tool_Event
{
    [Key]
    public int LogID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTime { get; set; }

    public int? ToolID { get; set; }

    public int? LastQuantity { get; set; }

    [StringLength(50)]
    public string Event { get; set; }

    [StringLength(50)]
    public string EditBy { get; set; }

    public int? NewQuantity { get; set; }
}