// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("Tool_Borrow")]
public partial class Tool_Borrow
{
    [Key]
    public int ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(50)]
    public string Job { get; set; }

    [Required]
    [StringLength(50)]
    public string BorrowBy { get; set; }

    [Required]
    [StringLength(50)]
    public string UserID { get; set; }

    [Required]
    [StringLength(50)]
    public string Reveral_Name { get; set; }

    public string Description { get; set; }

    public int Total { get; set; }

    [StringLength(50)]
    public string ApproveBy { get; set; }

    public int? Status { get; set; }

    [InverseProperty("Borrow")]
    public virtual ICollection<Tool_BorrowDetail> Tool_BorrowDetails { get; set; } = new List<Tool_BorrowDetail>();
}