// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("User_Access")]
public partial class User_Access
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    public string IDUser { get; set; }

    public string Store { get; set; }

    public string Tool { get; set; }

    public string UserManage { get; set; }
}