// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("User_Organize")]
public partial class User_Organize
{
    [Key]
    public int DepartmentType { get; set; }

    [StringLength(50)]
    public string VicePresident { get; set; }

    [StringLength(50)]
    public string AsstGM { get; set; }

    [StringLength(50)]
    public string SeniorManager1 { get; set; }

    [StringLength(50)]
    public string SeniorManager2 { get; set; }

    [StringLength(50)]
    public string Manager1 { get; set; }

    [StringLength(50)]
    public string Manager2 { get; set; }

    [StringLength(50)]
    public string Leader { get; set; }
}