// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SonodaSoftware.Data;

[Table("User_UserBase")]
public partial class User_UserBase
{
    [Key]
    public int ID { get; set; }

    public string Photo { get; set; }

    [StringLength(50)]
    public string BarCode { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [StringLength(500)]
    public string FirstName_ENG { get; set; }

    [StringLength(500)]
    public string LastName_ENG { get; set; }

    [StringLength(500)]
    public string FirstName_TH { get; set; }

    [StringLength(500)]
    public string LastName_TH { get; set; }

    [StringLength(256)]
    public string Position_name { get; set; }

    [StringLength(256)]
    public string Position_ID { get; set; }

    public int? Department_type { get; set; }

    [StringLength(256)]
    public string Department_name { get; set; }

    [StringLength(256)]
    public string Username { get; set; }

    [StringLength(256)]
    public string Password { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Createdon { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Modify_On { get; set; }

    public int? LoginFlag { get; set; }

    public int? Status { get; set; }

    [StringLength(50)]
    public string Nickname { get; set; }

    public int? Report_Person { get; set; }
}